Ivan/deredis rate limits
binary-com/perl-RateLimitations-Pluggable pull request #1
Opened 2016-10-13 12:13 UTC by basiliscos

2016-10-13 12:52 UTC, jy-binary commented
Remember to write a nice README

2016-10-17 09:59 UTC, chylli commented on t/10-compatibility.t
> +use strict;
Why this test named `compatibiliby` ?

2016-10-17 10:01 UTC, chylli commented on t/10-compatibility.t
> +  *CORE::GLOBAL::time = sub() { $current_time; };
I prefer `Test::MockTime`

2016-10-17 11:59 UTC, huiwang85 requested changes

2016-10-17 11:59 UTC, huiwang85 commented on README.md
> +RateLimitations::Pluggable - pluggabel manager of per-service rate limitations
A typo here: `pluggabel` should be `pluggable`.

2016-10-17 11:59 UTC, huiwang85 commented on README.md
> +`within_rate_limits` method, and checks whether limis are hits or not.
A typo: `limis` should be `limits`.

2016-10-17 11:59 UTC, huiwang85 commented on lib/RateLimitations/Pluggable.pm
> +RateLimitations::Pluggable - pluggabel manager of per-service rate limitations
A typo: `pluggabel` should be `pluggable`.

2016-10-17 11:59 UTC, huiwang85 commented on lib/RateLimitations/Pluggable.pm
> +C<within_rate_limits> method, and checks whether limis are hits or not.
A typo: `limis` should be `limits`.

2016-10-17 15:59 UTC, basiliscos commented on t/10-compatibility.t
> +use strict;
I tried to follow test-suite of `RateLimitations`, but a bit later I realised that I threw out most of `RateLimitations` functions (like flush, conversions etc.).

2016-10-17 22:51 UTC, chylli commented on lib/RateLimitations/Pluggable.pm
> +        my @service_limits =
To be honest, this line is too complex.

2016-10-18 08:49 UTC, basiliscos commented on lib/RateLimitations/Pluggable.pm
> +        my @service_limits =
Simplified

2016-10-18 23:35 UTC, tom-binary approved these changes
Looking good. Just a few minor comments, no blockers.

2016-10-18 23:35 UTC, binarytom commented on .travis.yml
> +    - "cpanm Test::More"
I'm surprised this works, since we have missing deps such as Moo. Normally I'd suggest `cpanm --installdeps .` with a `cpanfile`, see https://github.com/binary-com/perl-Date-Utility/ for an example.

2016-10-18 23:35 UTC, binarytom commented on lib/RateLimitations/Pluggable.pm
> +        for my $idx (0 .. @service_limits - 1) {
`$#service_limits` - or just track `$prev` and loop over the contents?

2016-10-18 23:35 UTC, binarytom commented on lib/RateLimitations/Pluggable.pm
> +=head2 within_rate_limits($service, $consumer)
It's slightly easier to link with a bare method name - `L<RateLimitations::Pluggable/within_rate_limits>`.

2016-10-18 23:35 UTC, binarytom commented on lib/RateLimitations/Pluggable.pm
> +            unless (ref($_[0]) // '') eq 'HASH';
could use [Type::Tiny](https://metacpan.org/pod/Types::Standard) for this, although the check is simple enough as-is.

2016-10-18 23:35 UTC, binarytom commented on lib/RateLimitations/Pluggable.pm
> +            if defined($_[0]) && (ref($_[0]) // '') ne 'CODE';
the `// ''` isn't needed here, I think?

2016-10-18 23:35 UTC, binarytom commented on lib/RateLimitations/Pluggable.pm
> +                if $limit - int($limit) != 0;
slightly odd way of writing `$limit != int($limit)`

2016-10-20 11:31 UTC, merged